### ISSUE TITLE
raise JSONDecodeError "Unexpected UTF-8 BOM (decode using utf-8-sig)"

### ISSUE THREAD

**Issue by sundisktop** [vikrambhat249/CurrencyExchange#1]
Hello, thanks for your nice script. It save me a lot of time.

When I try to use Download_historicalExchangeRates() it I got error:
TypeError: the JSON object must be str, not 'bytes'

But I fixed by replace:
                conn_url= requests.get(self.url)
                jd=conn_url.content
                data=json.loads(jd)
with:
               with urllib.request.urlopen(self.url) as url:
                 data = json.loads(url.read().decode())

**Comment by vikrambhat249** [comment]
Hi sundisktop,
Sometimes it also depends on which python IDE you are using.
You could also change the code to as below 
jd=conn_url.content.decode('utf-8')
data=json.loads(jd)

Hope this helps. Happy coding
